### ISSUE TITLE
[BUG] Fix Crowdsec Bouncer building successfully with invalid tarball.

### ISSUE THREAD

**Issue by thespad** [linuxserver/docker-mods#1033]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Name of mod

swag-crowdsec

### Name of base container

swag

### Current Behavior

Crowdsec Bouncer builds successfully with invalid tarball.

### Expected Behavior

Crowdsec Bouncer does not build successfully with invalid tarball.

### Steps To Reproduce

As above

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
No
```

### Container logs

```bash
No
```

**Comment by thespad** [comment]
Fixed in https://github.com/linuxserver/docker-mods/commit/9156249068e358e5c73389f5cab7c29efc8ca20d

**Comment by zichichi** [comment]
the bug is not fixed yet:

`**** installing docker and docker compose ****
**** Configuring CrowdSec nginx Bouncer ****
Copying over docker and docker-compose binaries
tar: invalid tar magic
**** Remote docker service dockersocket will be used ****
sed: /tmp/crowdsec/nginx/crowdsec_nginx.conf: No such file or directory
cp: cannot stat '/tmp/crowdsec/lua-mod/templates/*': No such file or directory
cp: cannot stat '/tmp/crowdsec/lua-mod/lib/*': No such file or directory
cp: cannot stat '/tmp/crowdsec/nginx/crowdsec_nginx.conf': No such file or directory
**** Successfully configured CrowdSec nginx Bouncer  ****
[pkg-install-init] **** Installing all mod packages ****
fetch http://dl-cdn.alpinelinux.org/alpine/v3.21/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.21/community/x86_64/APKINDEX.tar.gz
(1/16) Installing gettext-envsubst (0.22.5-r0)
(2/16) Installing libgomp (14.2.0-r4)
(3/16) Installing gettext-libs (0.22.5-r0)
(4/16) Installing gettext (0.22.5-r0)
(5/16) Installing lua5.1-libs (5.1.5-r13)
(6/16) Installing lua5.1 (5.1.5-r13)
(7/16) Installing lua-resty-http (0.17.2-r0)
(8/16) Installing luajit (2.1_p20240815-r0)
(9/16) Installing lua-resty-lrucache (0.13-r1)
(10/16) Installing lua-resty-core (0.1.31-r0)
(11/16) Installing nginx-mod-http-lua (1.26.3-r0)
(12/16) Installing lua-resty-string (0.15-r0)
(13/16) Installing lua-sec (1.3.2-r0)
(14/16) Installing lua5.1-socket (3.1.0-r1)
(15/16) Installing lua5.1-sec (1.3.2-r0)
(16/16) Installing lua5.1-cjson (2.1.0-r11)
Executing busybox-1.37.0-r12.trigger
OK: 187 MiB in 238 packages
[custom-init] No custom files found, skipping...
Auto-reload: Watching the following folders for changes to .conf files:
/config/nginx
[ls.io-init] done.
**** Disabling fail2ban Service ****
`

**Comment by thespad** [comment]
Oversight on my part, I forgot to force a rebuild once they fixed the upstream artefacts, it should be working with 1.1.2 now.
